FROM golang:1.22.2-alpine as build

RUN apk add --no-cache git

WORKDIR /src 

COPY go.sum /src/
COPY go.mod /src/

COPY main.go /src 

RUN go build main.go

FROM alpine as runtime


EXPOSE 8000

COPY --from=build /src/main /app/main
CMD [ "/app/main" ]
